name: Convert and Compile

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        course: [notes/mlnn]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Install TeX
      run: |
          sudo apt update
          sudo apt install latexmk
          sudo tlmgr update --self --all
          sudo tmlgr install biber

    - name: Build cli
      run: |
          cd cli/
          go install
          cd ..

    - name: Convert 
      run: courses convert ${{ matrix.course }}

    - name: Compile
      run: courses compile -s ${{ matrix.course }}
